# Numpy

## Numpy Array Oluşturmak

In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
a = np.array([1,2,3,4,5])

In [5]:
type(a)

numpy.ndarray

In [6]:
np.array([5.5,6.54,6,2,32.2])

array([ 5.5 ,  6.54,  6.  ,  2.  , 32.2 ])

In [8]:
np.array([5.5,6.54,6,2,32.2],dtype=int)

array([ 5,  6,  6,  2, 32])

# sıfırdan array oluşturma

In [11]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [13]:
np.ones((3,2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [14]:
np.full((3,2),3)

array([[3, 3],
       [3, 3],
       [3, 3]])

In [15]:
np.arange(0,20,2) #sıfırdan 20 ye kadar 2şerli sıralama

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
np.linspace(0,100,4, dtype=int) # 0 ile 100 arasında eşit uzaklıkta 4 sayı oluşturma

array([  0,  33,  66, 100])

In [24]:
np.random.normal(10 , 4 ,(3,2 )) #ortalama 10 standart sapması 4 arraylar oluşturma

array([[ 8.33010283, 13.99218339],
       [ 8.43989577,  9.7763669 ],
       [ 2.5309348 , 11.69420055]])

In [30]:
np.random.randint(0,20,(3,2)) #sıfırdan 20 ye ratgele sayı üretme

array([[19, 10],
       [ 0, 19],
       [19, 13]])